server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:CodeGeneratorDm://192.168.0.163:3306/oa?useSSL=false&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    username: root
    password: root

  thymeleaf:
    cache: false

  activiti:
    check-process-definitions: false